global.unlockHauntedBookshelf = false;  //flag for haunted bookshelf unlock
global.unlockHauntedBookshelfLibrarianHalf = false;  //librarian unlock half
global.unlockHauntedBookshelfJanitorHalf = false;  //janitor unlock half
global.hasInspectedMirror = false;  //flag for mirror inspection
global.wallPhase = false;  //wall phase ability unlocked
global.returnedCursedBook = false;  //cursed book returned
global.spokenWithLibrarian = false;  //spoken with librarian flag
global.librarianDialogueBranch = 0;  //tracks librarian dialogue branch
global.janitorDialogueBranch = 0;  //tracks janitor dialogue branch
global.janitorDisabled = false;  //janitor interaction disabled
global.librarianDisabled = false;  //librarian interaction disabled
global.HasCursedBook = false;  //player has obtained cursed book
global.lanternHasCursedFlame = false;  //flag for cursed flame in lantern
global.lanternLit = false;  //lantern lit flag
global.spiritAwakening = false;  //spirit awakening triggered
global.pedestalOccupied = false;  //pedestal occupied flag
global.inventory = [];  //initialize empty player inventory
global.isTalkingToLibrarian = false;  //librarian conversation flag
global.isTalkingToJanitor = false;  //janitor conversation flag
